import type { Metadata } from "next";
import "./globals.css";



import { montserrat300 } from "./fonts/montserrat";

export const metadata: Metadata = {
  title: "AI PDF Chatting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat300.className} ${montserrat300.className} antialiased relative min-h-screen overflow-hidden grid place-content-center`}
      >
        {children}
      </body>
    </html>
  );
}
